{{- range $name, $rule := .Values.additionalPrometheusRulesMap }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "otc-prometheus-exporter.name" $ }}-{{ $name }}
  namespace: {{ template "otc-prometheus-exporter.namespace" $ }}
  labels:
    {{- include "otc-prometheus-exporter.labels" $ | nindent 4 }}
    {{- with $rule.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    {{- toYaml $rule.groups | nindent 4 }}
{{- end }}
