{{- if .Values.prometheusRules.enabled }}
{{- range $namespace, $config := .Values.targets.namespaces }}
{{- $values := mustMergeOverwrite (deepCopy $.Values.targets.defaults) (default dict $config) }}
{{- if $values.enabled }}
{{- $name := $values.rules }}
{{- if ne (toString $name) "false" }}
{{- if or (empty $name) (eq (toString $name) "true") }}
  {{- $name = include "otc-prometheus-exporter.namespaceName" $namespace }}
{{- end }}
{{- $content := $.Files.Get (printf "alerts/%s.yaml" $name) }}
{{- if $content }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-alerts
  namespace: {{ template "otc-prometheus-exporter.namespace" $ }}
  labels:
{{ include "otc-prometheus-exporter.labels" $ | indent 4 }}
spec:
  {{- $content | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
